AWSTemplateFormatVersion: "2010-09-09"
Resources:
  myEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-03ededff12e34e59e
      InstanceType: t2.micro
      SecurityGroups:
         - !Ref mySecurityGroup

  mySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: Demo-security
      GroupDescription: "Demo Security Group"